package constants

const (
	COLLECTIONAGROECOLOGICALZONE    = "agroEcologicalZone"
	AGROECOLOGICALZONESTATUSTRUE    = true
	AGROECOLOGICALZONESTATUSFALSE   = false
	AGROECOLOGICALZONESTATUSACTIVE  = "Active"
	AGROECOLOGICALZONESTATUSDISABLE = "Disabled"
	AGROECOLOGICALZONESTATUSDELETED = "Deleted"
)
