package constants

const (
	COLLECTIONBANNEDITEM    = "bannedItem"
	BANNEDITEMSTATUSTRUE    = true
	BANNEDITEMSTATUSFALSE   = false
	BANNEDITEMSTATUSACTIVE  = "Active"
	BANNEDITEMSTATUSDISABLE = "Disabled"
	BANNEDITEMSTATUSDELETED = "Deleted"
)
