package constants

const (
	COLLECTIONCONTENTCOMMENT    = "contentComment"
	CONTENTCOMMENTSTATUSACTIVE  = "Active"
	CONTENTCOMMENTSTATUSDISABLE = "Disabled"
	CONTENTCOMMENTSTATUSDELETED = "Deleted"
)
