package constants

const (
	COLLECTIONCROPSEASON    = "cropseason"
	CROPSEASONSTATUSTRUE    = true
	CROPSEASONSTATUSFALSE   = false
	CROPSEASONSTATUSACTIVE  = "Active"
	CROPSEASONSTATUSDISABLE = "Disabled"
	CROPSEASONSTATUSDELETED = "Deleted"
)
