package constants

const (
	COLLECTIONDISTRICWEATHERDATA    = "districtWeatherData"
	DISTRICWEATHERDATASTATUSTRUE    = true
	DISTRICWEATHERDATASTATUSFALSE   = false
	DISTRICWEATHERDATASTATUSACTIVE  = "Active"
	DISTRICWEATHERDATASTATUSDISABLE = "Disabled"
	DISTRICWEATHERDATASTATUSDELETED = "Deleted"
)
