package constants

const (
	COLLECTIONLANGAUAGE    = "langauage"
	LANGAUAGESTATUSTRUE    = true
	LANGAUAGESTATUSFALSE   = false
	LANGAUAGESTATUSACTIVE  = "Active"
	LANGAUAGESTATUSDISABLE = "Disabled"
	LANGAUAGESTATUSDELETED = "Deleted"
)
