package constants

//LIVESTOCKVACCINATION Constants
const (
	LIVESTOCKVACCINATIONSTATUSACTIVE   = "Active"
	LIVESTOCKVACCINATIONSTATUSDISABLED = "Disabled"
	LIVESTOCKVACCINATIONSTATUSDELETED  = "Deleted"
)
