package constants

const (
	PRODUCTCONFIGSTATUSTRUE    = true
	PRODUCTCONFIGSTATUSFALSE   = false
	PRODUCTCONFIGSTATUSACTIVE  = "Active"
	PRODUCTCONFIGSTATUSDISABLE = "Disabled"
	PRODUCTCONFIGSTATUSDELETED = "Deleted"
)
