package constants

const (
	PROJECTFARMERSTATUSTRUE     = true
	PROJECTFARMERSTATUSFALSE    = false
	PROJECTFARMERSTATUSACTIVE   = "Active"
	PROJECTFARMERSTATUSDISABLED = "Disabled"
	PROJECTFARMERSTATUSDELETED  = "Deleted"
)
