package constants

//knowledgedomain
const (
	KNOWLEDGEDOMAINSTATUSTRUE     = true
	KNOWLEDGEDOMAINSTATUSFALSE    = false
	KNOWLEDGEDOMAINSTATUSACTIVE   = "Active"
	KNOWLEDGEDOMAINSTATUSDISABLED = "Disabled"
	KNOWLEDGEDOMAINSTATUSDELETED  = "Deleted"
)

//projectknowledgedomain
const (
	PROJECTKNOWLEDGEDOMAINSTATUSACTIVE   = "Active"
	PROJECTKNOWLEDGEDOMAINSTATUSDISABLED = "Disabled"
	PROJECTKNOWLEDGEDOMAINSTATUSDELETED  = "Deleted"
)

//SUBTOPIC
const (
	SUBTOPICSTATUSACTIVE   = "Active"
	SUBTOPICSTATUSDISABLED = "Disabled"
	SUBTOPICSTATUSDELETED  = "Deleted"
)

//Topic
const (
	TOPICSTATUSACTIVE   = "Active"
	TOPICSTATUSDISABLED = "Disabled"
	TOPICSTATUSDELETED  = "Deleted"
)

//SUBDOMAIN
const (
	SUBDOMAINSTATUSACTIVE   = "Active"
	SUBDOMAINSTATUSDISABLED = "Disabled"
	SUBDOMAINSTATUSDELETED  = "Deleted"
)
