package constants

const (
	PROJECTPARTNERSTATUSTRUE     = true
	PROJECTPARTNERSTATUSFALSE    = false
	PROJECTPARTNERSTATUSACTIVE   = "Active"
	PROJECTPARTNERSTATUSDISABLED = "Disabled"
	PROJECTPARTNERSTATUSDELETED  = "Deleted"
)
