package constants

const (
	PROJECTSTATESTATUSTRUE     = true
	PROJECTSTATESTATUSFALSE    = false
	PROJECTSTATESTATUSACTIVE   = "Active"
	PROJECTSTATESTATUSDISABLED = "Disabled"
	PROJECTSTATESTATUSDELETED  = "Deleted"
)
