package constants

const (
	PROJECTUSERSTATUSTRUE     = true
	PROJECTUSERSTATUSFALSE    = false
	PROJECTUSERSTATUSACTIVE   = "Active"
	PROJECTUSERSTATUSDISABLED = "Disabled"
	PROJECTUSERSTATUSDELETED  = "Deleted"
)
